In [2]:
import numpy as np

In [16]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [17]:
mu = np.mean(x, axis=1)
mu

array([2., 5.])

In [18]:
sigma = np.std(x, axis=1)
sigma

array([0.81649658, 0.81649658])

In [19]:
(1-2)/0.81649658

-1.224744872783178

In [20]:
m = np.size(x, 1)
m

3

In [21]:
mu_matrix = np.ones((m, 1)) * mu
mu_matrix

array([[2., 5.],
       [2., 5.],
       [2., 5.]])

In [22]:
sigma_matrix = np.ones((m, 1)) * sigma
sigma_matrix

array([[0.81649658, 0.81649658],
       [0.81649658, 0.81649658],
       [0.81649658, 0.81649658]])

In [23]:
mu_matrix

array([[2., 5.],
       [2., 5.],
       [2., 5.]])

In [55]:
# x_norm = (x - mu_matrix) .\ sigma_matrix

x_norm = (x.transpose() - mu_matrix) / sigma_matrix
x_norm

array([[-1.22474487, -1.22474487],
       [ 0.        ,  0.        ],
       [ 1.22474487,  1.22474487]])

In [56]:
# Standardization from scikit-learn
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit_transform(x.transpose())

array([[-1.22474487, -1.22474487],
       [ 0.        ,  0.        ],
       [ 1.22474487,  1.22474487]])

In [57]:
# With normalization
from sklearn.preprocessing import normalize
normalize(x)

array([[0.26726124, 0.53452248, 0.80178373],
       [0.45584231, 0.56980288, 0.68376346]])